version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pharma_user
      POSTGRES_PASSWORD: pharma_password
      POSTGRES_DB: pharma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharma_user -d pharma_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pharma_user:pharma_password@db:5432/pharma_db
      - FDA_API_KEY=${FDA_API_KEY}
      - CDC_API_KEY=${CDC_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn src.backend.app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: data_pipeline/Dockerfile
    environment:
      - DATABASE_URL=postgresql://pharma_user:pharma_password@db:5432/pharma_db
      - FDA_API_KEY=${FDA_API_KEY}
      - CDC_API_KEY=${CDC_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: python data_pipeline/orchestration/run_worker.py

volumes:
  postgres_data:
